Lab Task 1

In [2]:
num=[2, 1, 6, 5]
def is_even(num):
    return num%2==0
en=filter(is_even, num)
squared_list = [n ** 2 for n in en]
print(squared_list)

[4, 36]


In [3]:
def is_odd(num):
    return num%2!=0
od=filter(is_odd, num)
cubed_list = [n ** 2 for n in od]
print(cubed_list)

[1, 25]


In [6]:
merged=squared_list+cubed_list
print(sorted(merged))

[1, 4, 25, 36]


Lab Task 2

In [12]:
dict={}
for i in range(5):
    name=input("Enter name:")
    category=input("Enter category:")
    value=int(input("Enter value:"))
    
    dict[name]=[name, category, value]

print(dict)


Enter name:f
Enter category:f
Enter value:3
Enter name:g
Enter category:g
Enter value:5
Enter name:bg
Enter category:h
Enter value:6
Enter name:h
Enter category:g
Enter value:8
Enter name:v
Enter category:g
Enter value:7
{'f': ['f', 'f', 3], 'g': ['g', 'g', 5], 'bg': ['bg', 'h', 6], 'h': ['h', 'g', 8], 'v': ['v', 'g', 7]}


In [13]:
res_max= max(dict, key=dict.get)
print(res_max)

res_min = min(dict, key=dict.get)
print(res_min)

v
bg


In [19]:
asc = {k: v for k, v in sorted(dict.items(), key=lambda item: item[1])}

print(asc)

{'bg': ['bg', 'h', 6], 'f': ['f', 'f', 3], 'g': ['g', 'g', 5], 'h': ['h', 'g', 8], 'v': ['v', 'g', 7]}


Lab Task 3

In [28]:
import numpy as np
x=7
y=3
diff=lambda a, b:abs(x-y)
data = [10,20,30,40]
data['normalized_values'] = lambda x: (x - min_val) / (max_val - min_val)


TypeError: list indices must be integers or slices, not str

Lab Task 5

In [ ]:
import numpy as np


performance_scores = np.array([
    [85, 90, 78],  
    [92, 88, 95],  
    [70, 75, 80],  
    [95, 98, 92]   
])

print("Original Scores:\n", performance_scores, "\n")

average_scores = np.mean(performance_scores, axis=1)
print("Average Scores per System:", average_scores, "\n")

sorted_indices_asc = np.argsort(average_scores)
print("Ascending Sorted Indices:", sorted_indices_asc, "\n")
sorted_indices_desc = sorted_indices_asc[::-1]

print("--- System Ranking (Best to Worst) ---")
for i in sorted_indices_desc:
    print(f"System {chr(65+i)} (Avg: {average_scores[i]:.2f}): {performance_scores[i]}")

print("\n--- Ranked Average Scores ---")
ranked_averages = average_scores[sorted_indices_desc]
for rank, avg_score in enumerate(ranked_averages):
    print(f"Rank {rank+1}: {avg_score:.2f}")


Original Scores:
 [[85 90 78]
 [92 88 95]
 [70 75 80]
 [95 98 92]] 

Average Scores per System: [84.33333333 91.66666667 75.         95.        ] 

Ascending Sorted Indices: [2 0 1 3] 



NameError: name 'rder' is not defined